### ISSUE TITLE
Rollover calculation doubt

### ISSUE THREAD

**Issue by yeikiu** [kraken-fees-calculator/kraken-fees-calculator.github.io#5]
Hey, thanks for such a well written class!

I was trying to simulate the 50 ETH short movement described [here](https://support.kraken.com/hc/en-us/articles/201893638-Overview-of-trading-fees-on-Kraken) with your calculator. Everything matches except for the Rollover fee which would always return 50% less than it should.

I commented the 1st operator in your line 80 in order to match their example:

(/* (1-(1/options.trade.leverage)) *  */options.trade.amount * options.trade.price_in * margin_rollover_fees / 100 * Math.ceil(duration/4))

Why do you apply  (1-(1/options.trade.leverage)) to the calculation?

Thanks!

**Comment by tomav** [comment]
To be honest,  I have myself a doubt on this calculation.
If you want to submit a PR I'll merge it.

**Comment by Valenorious** [comment]
I concur that the rollover fee calculation is incorrect. According to the note at the bottom of the Kraken Help page it should be calculated over the entire value of the order. Not only the part that is loned.

https://support.kraken.com/hc/en-us/articles/206161568-What-are-the-fees-for-margin-trading-

The code as it is working now does not seem to be updated with the above correction.

**Comment by tomav** [comment]
Merged, thanks guys.

**Comment by Valenorious** [comment]
Am I under the mistaken impression that this would have updated the https://kraken-fees-calculator.github.io/ page too?

**Comment by tomav** [comment]
Sorry guys, some files were missing. Should be better now.
I also updated `README`.
Please let me know.

**Comment by Valenorious** [comment]
Yep, calculation seems correct now.
